# Configuration Serveur
server:
  port: 8081
  servlet:
    context-path: /exam_spring
  # Configuration de la Base de donnees
spring:
  mvc:
   throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  main:
    allow-circular-references: true
  security:
    oauth2:
      resource-server:
        jwt:
           issuer-uri: http://localhost:8180/realms/exam-spring-realm
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project_management
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

app:
  keycloak:
        admin:
          password: xxxx
          username: xxxxx
        client-id: exam_spring
        client-secret: NZOymsJieajLtISvIs4cncwokfXI9JYB
        grant-type: password
        login:
          url: http://localhost:8180/realms/exam-spring-realm/protocol/openid-connect/token
        realm:
          name: exam-spring-realm
        server:
          url: http://localhost:8180
keycloak:
        ssl-required: external
        use-resource-role-mapping: true

jwt:
    auth:
      converter:
        resource-id: exam-spring
        principal-attribute: preferred_username
